### ISSUE TITLE
lmdb.Error: cache/exp1000train: No such file or directory

### ISSUE THREAD

**Issue by JoshMalters** [OhadRubin/SmBop#2]
Hi there! Thanks for putting this repo up! After reading the paper I was excited to try and mess around with it. As is, it appears that `SmbopSpiderDatasetReader` is expecting some sort of cached files? 

```
2021-04-21 20:51:26,983 - CRITICAL - root - Uncaught exception
Traceback (most recent call last):
  File "exec.py", line 140, in <module>
    run()
  File "exec.py", line 131, in run
    train_model(
  File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/commands/train.py", line 236, in train_model
    model = _train_worker(
  File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/commands/train.py", line 453, in _train_worker
    train_loop = TrainModel.from_params(
  File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 589, in from_params
    return retyped_subclass.from_params(
  File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 621, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 199, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 307, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 341, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 589, in from_params
    return retyped_subclass.from_params(
  File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 623, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/Users/maltersj/Documents/School/DL/SmBop/smbop/dataset_readers/spider.py", line 68, in __init__
    self.cache = TensorCache(cache_directory)
  File "/Users/maltersj/Documents/School/DL/SmBop/smbop/utils/cache.py", line 126, in __init__
    self.lmdb_env = lmdb.open(
lmdb.Error: cache/exp1000train: No such file or directory
```

**Comment by Young1993** [comment]
> Hi there! Thanks for putting this repo up! After reading the paper I was excited to try and mess around with it. As is, it appears that `SmbopSpiderDatasetReader` is expecting some sort of cached files?
> 
> ```
> 2021-04-21 20:51:26,983 - CRITICAL - root - Uncaught exception
> Traceback (most recent call last):
>   File "exec.py", line 140, in <module>
>     run()
>   File "exec.py", line 131, in run
>     train_model(
>   File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/commands/train.py", line 236, in train_model
>     model = _train_worker(
>   File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/commands/train.py", line 453, in _train_worker
>     train_loop = TrainModel.from_params(
>   File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 589, in from_params
>     return retyped_subclass.from_params(
>   File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 621, in from_params
>     kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
>   File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 199, in create_kwargs
>     constructed_arg = pop_and_construct_arg(
>   File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 307, in pop_and_construct_arg
>     return construct_arg(class_name, name, popped_params, annotation, default, **extras)
>   File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 341, in construct_arg
>     return annotation.from_params(params=popped_params, **subextras)
>   File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 589, in from_params
>     return retyped_subclass.from_params(
>   File "/Users/maltersj/miniconda/envs/smbop/lib/python3.8/site-packages/allennlp/common/from_params.py", line 623, in from_params
>     return constructor_to_call(**kwargs)  # type: ignore
>   File "/Users/maltersj/Documents/School/DL/SmBop/smbop/dataset_readers/spider.py", line 68, in __init__
>     self.cache = TensorCache(cache_directory)
>   File "/Users/maltersj/Documents/School/DL/SmBop/smbop/utils/cache.py", line 126, in __init__
>     self.lmdb_env = lmdb.open(
> lmdb.Error: cache/exp1000train: No such file or directory
> ```

me too

**Comment by OhadRubin** [comment]
I think you just need to create a folder named "cache" and it will solve that

**Comment by JoshMalters** [comment]
Yup that was it... awkwardly I tried that under an incorrect directoy. The `if os.path.isfile(filename):` check was throwing me off. Thanks for the reply!
