### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by puritysarah** [OhadRubin/SmBop#54]
When I run exec.py, I faced the error below:

Traceback (most recent call last):
  File "exec.py", line 146, in <module>
    run()
  File "exec.py", line 137, in run
    train_model(
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/commands/train.py", line 236, in train_model
    model = _train_worker(
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/commands/train.py", line 453, in _train_worker
    train_loop = TrainModel.from_params(
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/common/from_params.py", line 589, in from_params
    return retyped_subclass.from_params(
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/common/from_params.py", line 623, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/commands/train.py", line 658, in from_partial_objects
    "train": data_loader.construct(reader=dataset_reader, data_path=train_data_path)
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/common/lazy.py", line 80, in construct
    return self.constructor(**contructor_kwargs)
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/common/lazy.py", line 64, in constructor_to_use
    return self._constructor.from_params(  # type: ignore[union-attr]
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/common/from_params.py", line 589, in from_params
    return retyped_subclass.from_params(
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/common/from_params.py", line 623, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/data/data_loaders/multiprocess_data_loader.py", line 281, in __
init__
    deque(self.iter_instances(), maxlen=0)
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/data/data_loaders/multiprocess_data_loader.py", line 349, in it
er_instances
    for instance in Tqdm.tqdm(
  File "/home/puritysarah/.local/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/puritysarah/anaconda3/envs/py38/lib/python3.8/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 192, in read
    for instance in self._multi_worker_islice(self._read(file_path)):  # type: ignore
  File "/home/puritysarah/SmBop/smbop/dataset_readers/spider.py", line 180, in _read
    yield from self._read_examples_file(file_path)
  File "/home/puritysarah/SmBop/smbop/dataset_readers/spider.py", line 214, in _read_examples_file
    ins = self.create_instance(ex)
  File "/home/puritysarah/SmBop/smbop/dataset_readers/spider.py", line 244, in create_instance
    ins = self.text_to_instance(
  File "/home/puritysarah/SmBop/smbop/dataset_readers/spider.py", line 265, in text_to_instance
    tree_dict = msp.parse(sql)
...
File "/home/puritysarah/.local/lib/python3.8/site-packages/pyparsing/core.py", line 907, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/puritysarah/.local/lib/python3.8/site-packages/pyparsing/core.py", line 801, in _parseNoCache
    pre_loc = self.preParse(instring, loc)
  File "/home/puritysarah/.local/lib/python3.8/site-packages/pyparsing/core.py", line 751, in preParse
    loc = self._skipIgnorables(instring, loc)
  File "/home/puritysarah/.local/lib/python3.8/site-packages/pyparsing/core.py", line 743, in _skipIgnorables
    loc, dummy = e._parse(instring, loc)
  File "/home/puritysarah/.local/lib/python3.8/site-packages/pyparsing/core.py", line 903, in _parseCache
    value = cache.get(lookup)
  File "/home/puritysarah/.local/lib/python3.8/site-packages/pyparsing/util.py", line 109, in get
    return cache_get(key, not_in_cache)
RecursionError: maximum recursion depth exceeded

I do not know where this comes from...

**Comment by OhadRubin** [comment]
Try increasing the number [here](https://github.com/OhadRubin/SmBop/blob/d38a15c64f73c50adc406ea8b155a06fc9f5a116/smbop/utils/moz_sql_parser/sql_parser.py#L40) from 2000

**Comment by puritysarah** [comment]
Thanks @OhadRubin :)
